# Generated by Django 6.0.1 on 2026-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('reource_type', models.CharField(choices=[('png', 'PNG'), ('image', 'Scrrenshot'), ('link', 'Link'), ('notes', 'Notes')], max_length=10)),
                ('files', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('current_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
