# Generated by Django 6.0.1 on 2026-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='reource_type',
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('png', 'PNG'), ('image', 'Screenshot'), ('link', 'Link'), ('notes', 'Notes')], max_length=10, null=True),
        ),
    ]
