# Generated by Django 6.0.1 on 2026-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_core', '0003_resources_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='tag',
            field=models.ManyToManyField(to='vault_core.tag'),
        ),
    ]
